"""Loading `.osca/` metadata of a study repository."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import pathspec
import yaml

from .markers import DEFAULT_MARKER

OSCA_DIR = ".osca"
PROJECT_FILE = f"{OSCA_DIR}/project.yaml"
SYNC_FILE = f"{OSCA_DIR}/sync.yaml"
STATUS_FILE = f"{OSCA_DIR}/status.json"
REPORTS_DIR = f"{OSCA_DIR}/reports"


class ConfigError(RuntimeError):
    pass


@dataclass
class Project:
    root: Path
    raw: dict[str, Any]
    id: str
    upstream_remote: str
    upstream_url: str
    upstream_branch: str
    track: str
    tag_pattern: str
    mirror_branch: str
    study_branch: str
    marker: str
    include: list[str] = field(default_factory=list)
    exclude: list[str] = field(default_factory=list)
    generated: list[str] = field(default_factory=list)

    @property
    def scope(self) -> pathspec.GitIgnoreSpec:
        return pathspec.GitIgnoreSpec.from_lines(self.include)

    @property
    def scope_exclude(self) -> pathspec.GitIgnoreSpec:
        return pathspec.GitIgnoreSpec.from_lines(self.exclude)

    @property
    def generated_spec(self) -> pathspec.GitIgnoreSpec:
        return pathspec.GitIgnoreSpec.from_lines(self.generated)

    def in_scope(self, path: str) -> bool:
        return (
            self.scope.match_file(path)
            and not self.scope_exclude.match_file(path)
            and not self.generated_spec.match_file(path)
        )


def find_project_root(start: Path) -> Path | None:
    for d in [start, *start.parents]:
        if (d / PROJECT_FILE).is_file():
            return d
    return None


def load_project(root: Path) -> Project:
    path = root / PROJECT_FILE
    if not path.is_file():
        raise ConfigError(f"{PROJECT_FILE} not found in {root}")
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    try:
        up = raw["upstream"]
        study = raw.get("study", {})
        scope = raw.get("scope", {})
        return Project(
            root=root,
            raw=raw,
            id=raw["project"],
            upstream_remote=up.get("remote", "upstream"),
            upstream_url=up["repository"],
            upstream_branch=up["branch"],
            track=up.get("track", "tags"),
            tag_pattern=up.get("tag_pattern", r"^v\d+\.\d+\.\d+$"),
            mirror_branch=up.get("mirror_branch", f"mirror/{up['branch']}"),
            study_branch=study.get("branch", "study/zh-CN"),
            marker=study.get("marker", DEFAULT_MARKER),
            include=list(scope.get("include", ["**"])),
            exclude=list(scope.get("exclude", [])),
            generated=list(study.get("generated", [])),
        )
    except KeyError as e:
        raise ConfigError(f"{PROJECT_FILE}: missing required key {e}") from e


def load_sync(root: Path) -> dict[str, Any]:
    path = root / SYNC_FILE
    if not path.is_file():
        raise ConfigError(f"{SYNC_FILE} not found; run `osca init --anchor <ref>` first")
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not data.get("anchor", {}).get("upstream_commit"):
        raise ConfigError(f"{SYNC_FILE}: anchor.upstream_commit is missing")
    return data


def write_sync(root: Path, data: dict[str, Any]) -> None:
    text = (
        "# Generated by `osca`. Do not edit by hand.\n"
        "# anchor.upstream_commit = the upstream commit this study branch corresponds to.\n"
        + yaml.safe_dump(data, sort_keys=False, allow_unicode=True)
    )
    (root / SYNC_FILE).write_text(text, encoding="utf-8")


def anchor_commit(root: Path) -> str:
    return load_sync(root)["anchor"]["upstream_commit"]
